language: node_js
node_js:
  10.0.0
branches:
  # builds all branches
  /.*/
jobs:
  include:
    stage: "Prepare"
      npm install -g ionic cordova
    stage: "Build, test, lint"
      script:
        ionic build --prod --service-worker
    stage: "Deploy"
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN 
      keep-history: true
      on:
        branch: master
      local_dir: www
    stage: "After"
      npm install -g travis-deploy-once
      npm run semantic-release
  