language: node_js
node_js:
  8.9.3
branches:
  only:
    develop
before_script:
  npm install -g ionic cordova
script:
  ionic build --prod --service-worker
after_success: 
  npm install -g travis-deploy-once
  npm run semantic-release
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master
  local_dir: www