--- 
branches: /.*/
jobs: 
  include: 
    - 
      stage: "prepare"
      script: "npm install -g ionic cordova"
    - 
      script: "ionic build --prod --service-worker"
      stage: "build, test, lint"
    - 
      github-token: $GITHUB_TOKEN
      keep-history: true
      local_dir: www
      provider: pages
      skip-cleanup: true
      stage: deploy
      true: 
        branch: master
    - 
      stage: "after npm install -g travis-deploy-once npm run semantic-release"
language: node_js
node_js: "10.0.0"

  